# Generated by Django 4.0.2 on 2022-02-13 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapi.folder'),
            preserve_default=False,
        ),
    ]
