# Generated by Django 4.0.2 on 2022-02-14 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_folder_document_document_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=60)),
                ('short_description', models.CharField(max_length=80)),
                ('long_description', models.CharField(max_length=140)),
            ],
        ),
    ]
