# Generated by Django 4.0.2 on 2022-02-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='short_description',
        ),
    ]
