# Generated by Django 4.0.2 on 2022-02-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_topic_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='topics',
            field=models.ManyToManyField(to='myapi.Topic'),
        ),
    ]
