# Generated by Django 4.0.2 on 2022-02-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_folder_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='topics',
            field=models.ManyToManyField(to='myapi.Topic'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
