# Generated by Django 4.0.2 on 2022-02-14 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_alter_document_topics_alter_folder_topics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file_name',
            new_name='short_description',
        ),
    ]
