# Generated by Django 4.0.2 on 2022-02-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0009_rename_file_name_document_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folder_name',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
