# Generated by Django 4.0.2 on 2022-02-15 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0010_alter_folder_folder_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='myapi.folder'),
        ),
    ]
