# Generated by Django 4.0.2 on 2022-02-15 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0012_alter_document_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='short_description',
            field=models.CharField(max_length=140),
        ),
    ]
