# Generated by Django 4.0.2 on 2022-02-15 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_alter_document_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='short_description',
            new_name='document_short_description',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='topics',
        ),
        migrations.AddField(
            model_name='folder',
            name='folder_short_description',
            field=models.CharField(default='Folder Short Desc', max_length=140),
            preserve_default=False,
        ),
    ]
