# Generated by Django 4.0.2 on 2022-02-15 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0014_rename_short_description_document_document_short_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='topics',
            new_name='topic',
        ),
    ]
